---
title: "lab 6 warmup"
output: 
  html_document: 
    keep_md: yes
date: "2024-01-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("tidyverse")
```

## Warm-up

### 1. Load the `bison.csv` data.

```{r}
bison <- read_csv("data/bison.csv")
```

### 2. What are the dimesions and structure of the data?

```{r}
dim(bison)
```

```{r}
str(bison)
```

### 3. We are only interested in code, sex, weight, year of birth. Restrict the data to these variables and store the dataframe as a new object.

```{r}
names(bison)
```

```{r}
bison_new <- bison %>% 
  select("data_code", "animal_sex", "animal_weight", "animal_yob")
```

### 4. Pull out the animals born between 1980-1990.

```{r}
bison_new%>% 
  filter(between(animal_yob, 1980, 1990))
```

```{r}
bison_new %>% 
  filter(animal_yob>=1980 & animal_yob<=1990)
```

### 5. How many male and female bison are represented between 1980-1990?

```{r}
males <- bison_new %>% 
  filter(between(animal_yob, 1980, 1990)) %>% 
  filter(animal_sex=="M")
```

```{r}
females <- bison_new %>% 
  filter(between(animal_yob, 1980, 1990)) %>% 
  filter(animal_sex=="F")
```

```{r}
table(males$animal_sex)
table(females$animal_sex)
```

### 6. Between 1980-1990, were males or females larger on average?

```{r}
mean(males$animal_weight)
mean(females$animal_weight)
```





